In [71]:
# pip install tensorflow

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.11.0'

In [3]:
df=pd.read_csv('lymphography.csv')

In [4]:
df.head()

3  4  2  1  1.1  1.2  1.3  1.4  2.1  1.5  2.2  2.3  2.4  4.1  8  1.6  1.7  \
0  2  3  2  1    1    2    2    1    2    1    3    3    2    3  4    2    2   
1  3  3  2  2    2    2    2    2    2    1    4    3    3    4  8    3    2   
2  3  3  1  1    1    1    2    1    2    1    3    3    4    4  4    3    1   
3  2  3  1  1    1    1    1    1    1    1    2    2    4    3  5    1    2   
4  2  2  1  1    1    1    1    1    2    1    3    3    3    3  6    3    1   

   2.5  2.6  
0    2    2  
1    2    7  
2    2    6  
3    2    1  
4    2    4

In [5]:
df.shape

(147, 19)

In [6]:
with open('lymphographynames.txt') as fo:
    for rec in fo:
        print(rec.split(':')[0])
    

Citation Request
   This lymphography domain was obtained from the University Medical Centre,

   Institute of Oncology, Ljubljana, Yugoslavia.  Thanks go to M. Zwitter and 

   M. Soklic for providing the data.  Please include this citation if you plan

   to use this database.



1. Title


2. Sources
    (a) See Above.

    (b) Donors
                University E.Kardelj

                Faculty for electrical engineering

                Trzaska 25

                61000 Ljubljana (tel.


                Bojan Cestnik

                Jozef Stefan Institute

                Jamova 39

                61000 Ljubljana

                Yugoslavia (tel.
   (c) Date


3. Past Usage
    1. Cestnik,G., Konenenko,I, & Bratko,I. (1987). Assistant-86
       Knowledge-Elicitation Tool for Sophisticated Users.  In I.Bratko

       & N.Lavrac (Eds.) Progress in Machine Learning, 31-45, Sigma Press.

       -- Assistant-86
    2. Clark,P. & Niblett,T. (1987). Induction in Noisy Domains.  In

   

In [7]:
df.columns = ['class', 'lymphatics', 'block of affere', 'bl. of lymph. c', 'bl. of lymph. s', 'by pass', 'extravasates', 'regeneration of', 'early uptake in', 'lym.nodes dimin', 'lym.nodes enlar', 'changes in lym', 'defect in node', 'changes in node', 'changes in stru', 'special forms', 'dislocation of', 'exclusion of no', 'no. of nodes in']

In [8]:
df

class  lymphatics  block of affere  bl. of lymph. c  bl. of lymph. s  \
0        2           3                2                1                1   
1        3           3                2                2                2   
2        3           3                1                1                1   
3        2           3                1                1                1   
4        2           2                1                1                1   
..     ...         ...              ...              ...              ...   
142      3           3                2                1                1   
143      2           2                1                1                1   
144      3           2                2                1                1   
145      2           2                1                1                1   
146      2           2                2                2                1   

     by pass  extravasates  regeneration of  early uptake in  lym.nodes dimin  \
0          2             2                1                2                1   
1          2             2                2                2                1   
2          1             2                1                2                1   
3          1             1                1                1                1   
4          1             1                1                2                1   
..       ...           ...              ...              ...              ...   
142        2             2                1                2                1   
143        1             1                1                1                1   
144        1             2                1                2                1   
145        1             1                1                2                1   
146        2             2                1                2                1   

     lym.nodes enlar  changes in lym  defect in node  changes in node  \
0                  3               3               2                3   
1                  4               3               3                4   
2                  3               3               4                4   
3                  2               2               4                3   
4                  3               3               3                3   
..               ...             ...             ...              ...   
142                2               2               4                3   
143                1               1               1                1   
144                3               3               3                3   
145                2               2               4                2   
146                3               3               4                3   

     changes in stru  special forms  dislocation of  exclusion of no  \
0                  4              2               2                2   
1                  8              3               2                2   
2                  4              3               1                2   
3                  5              1               2                2   
4                  6              3               1                2   
..               ...            ...             ...              ...   
142                5              2               2                2   
143                3              1               2                2   
144                8              3               2                2   
145                2              1               2                2   
146                4              3               2                2   

     no. of nodes in  
0                  2  
1                  7  
2                  6  
3                  1  
4                  4  
..               ...  
142                4  
143                1  
144                4  
145                1  
146                6  

[147 rows x 19 columns]

In [95]:
X = df.iloc[:,1:-1].values
y = df.iloc[:,0].values

(147, 19)

In [112]:
X_train, y_train, X_test, y_test = train_test_split(
    X,y, test_size=0.2, random_state=42, shuffle=True)

In [118]:
X_train.shape

(117, 19)

In [122]:
model = keras.Sequential([
    keras.layers.Dense(4, input_shape=(None,19), activation='relu'),
    keras.layers.Dense(2, activation='sigmoid')
])
 
# Compiling the model
model.compile(optimizer='adam',
              loss=keras.losses.SparseCategoricalCrossentropy(),
              metrics=['accuracy'])
 
# fitting the model
model.fit(X, y, epochs=10, batch_size=8)

Epoch 1/10


InvalidArgumentError: Graph execution error:

Detected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):
    File "C:\Users\tariv\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Users\tariv\anaconda3\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Users\tariv\anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "C:\Users\tariv\anaconda3\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
      app.start()
    File "C:\Users\tariv\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 677, in start
      self.io_loop.start()
    File "C:\Users\tariv\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
      self.asyncio_loop.run_forever()
    File "C:\Users\tariv\anaconda3\lib\asyncio\base_events.py", line 601, in run_forever
      self._run_once()
    File "C:\Users\tariv\anaconda3\lib\asyncio\base_events.py", line 1905, in _run_once
      handle._run()
    File "C:\Users\tariv\anaconda3\lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "C:\Users\tariv\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 471, in dispatch_queue
      await self.process_one()
    File "C:\Users\tariv\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 460, in process_one
      await dispatch(*args)
    File "C:\Users\tariv\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 367, in dispatch_shell
      await result
    File "C:\Users\tariv\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 662, in execute_request
      reply_content = await reply_content
    File "C:\Users\tariv\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 360, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "C:\Users\tariv\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 532, in run_cell
      return super().run_cell(*args, **kwargs)
    File "C:\Users\tariv\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2863, in run_cell
      result = self._run_cell(
    File "C:\Users\tariv\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2909, in _run_cell
      return runner(coro)
    File "C:\Users\tariv\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "C:\Users\tariv\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3106, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "C:\Users\tariv\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3309, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "C:\Users\tariv\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3369, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\tariv\AppData\Local\Temp\ipykernel_10212\1955270755.py", line 12, in <cell line: 12>
      model.fit(X, y, epochs=10, batch_size=8)
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\engine\training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\engine\training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\engine\training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\engine\training.py", line 1222, in run_step
      outputs = model.train_step(data)
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\engine\training.py", line 1024, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\engine\training.py", line 1082, in compute_loss
      return self.compiled_loss(
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\losses.py", line 152, in __call__
      losses = call_fn(y_true, y_pred)
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\losses.py", line 284, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\losses.py", line 2098, in sparse_categorical_crossentropy
      return backend.sparse_categorical_crossentropy(
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\backend.py", line 5633, in sparse_categorical_crossentropy
      res = tf.nn.sparse_softmax_cross_entropy_with_logits(
Node: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'
Received a label value of 3 which is outside the valid range of [0, 2).  Label values: 2 3 2 3 1 2 2 2
	 [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_61064]

In [110]:

from collections import Counter
print(Counter(y))

Counter({2: 81, 3: 60, 4: 4, 1: 2})


In [11]:
print(X)

[[3 2 1 ... 2 2 2]
 [3 2 2 ... 3 2 2]
 [3 1 1 ... 3 1 2]
 ...
 [2 2 1 ... 3 2 2]
 [2 1 1 ... 1 2 2]
 [2 2 2 ... 3 2 2]]


In [12]:
print(y)

[2 3 3 2 2 2 2 3 3 2 2 2 3 4 2 2 2 2 2 3 3 2 2 3 3 3 3 2 3 3 3 2 2 2 2 4 3
 3 3 3 3 2 2 4 3 2 2 2 2 2 3 2 2 2 3 3 2 3 2 3 2 3 2 2 3 3 2 3 3 2 3 2 3 3
 2 2 2 1 3 3 2 3 3 3 2 2 2 3 2 3 2 2 2 3 3 2 2 2 2 3 2 2 2 2 3 2 3 2 2 2 3
 2 3 3 3 3 2 3 3 2 2 2 2 2 3 2 2 3 2 2 3 3 2 2 2 1 3 2 4 2 3 2 3 2 3 2 2]


In [13]:
df.isnull().sum()

class              0
lymphatics         0
block of affere    0
bl. of lymph. c    0
bl. of lymph. s    0
by pass            0
extravasates       0
regeneration of    0
early uptake in    0
lym.nodes dimin    0
lym.nodes enlar    0
changes in lym     0
defect in node     0
changes in node    0
changes in stru    0
special forms      0
dislocation of     0
exclusion of no    0
no. of nodes in    0
dtype: int64

In [14]:
Counter(y)

Counter({2: 81, 3: 60, 4: 4, 1: 2})

In [15]:
from collections import Counter
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=0)
X,y =  ros.fit_resample(X,y)
# print(sorted(Counter(X).items()),y.shape)

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)

In [17]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [18]:
ann = tf.keras.models.Sequential()

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [20]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [21]:
# activation = softmax for categorical
ann.add(tf.keras.layers.Dense(units=1, activation='softmax'))

In [54]:
# for non-binary categorical_crossentroopy
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [23]:
ann.fit(X_train, y_train, batch_size=32, epochs = 100)

Epoch 1/100
9/9 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 2/100
9/9 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 3/100
9/9 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 4/100
9/9 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 5/100
9/9 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 6/100
9/9 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 7/100
9/9 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 8/100
9/9 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 9/100
9/9 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 10/100
9/9 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accura

9/9 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 82/100
9/9 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 83/100
9/9 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 84/100
9/9 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 85/100
9/9 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 86/100
9/9 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 87/100
9/9 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 88/100
9/9 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 89/100
9/9 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2394
Epoch 90/100
9/9 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 

In [24]:
from sklearn.model_selection import GridSearchCV

In [25]:
parameter = {
    'C':[0.1,0.15,0.2,0.25,0.3,0.35,0.4,0.45,0.5,0.55,0.6],
}

In [26]:
clf = GridSearchCV(estimator=ann, param_grid=parameter, scoring='accuracy', cv=5, n_jobs=4, return_train_score=True)

In [42]:
# gridsearch = clf.fit(X_train,y_train)
# # clf.fit(X_train, y_train)
# 
# # print(clf.best_params_)
# 
# # print(clf.best_score_)

In [111]:
# from imblearn.over_sampling import SMOTE
# sm = SMOTE(random_state=42)
# X_res,y_res = sm.fit_resample(X,y)

In [41]:
# score = ann.fit(X_test, y_test, batch_size=64, epochs = 100)

In [129]:
ann.metrics_names

['loss', 'accuracy']

In [53]:
ann.evaluate(X_test,y_test,batch_size=10)

7/7 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2923


[0.0, 0.29230770468711853]

In [35]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [36]:
from keras.wrappers.scikit_learn import KerasClassifier

In [39]:
# def getModel(optimizer):
#     model = Sequential()
#     model.add(Dense(2, activation='relu', input_shape=X_train.shape[1:]))
#     model.add(Dense(2, activation='sigmoid'))
#     model.compile(optimizer=optimizer , loss = tf.losses.binary_crossentropy , metrics=['accuracy'])
#     return model
# 
# 
# optimizer = ['SGD', 'RMSprop', 'Adagrad', 'Adadelta', 'Adam', 'Adamax', 'Nadam']
# epochs = [10, 50, 100]
# 
# param_grid = dict(epochs=epochs, optimizer=optimizer)
# 
# Kmodel = KerasClassifier(build_fn=getModel, verbose=1)
# grid = GridSearchCV(estimator=Kmodel, param_grid=param_grid, scoring='accuracy', n_jobs=-1, refit='boolean')
# grid_result = grid.fit(X_train, y_train)

In [45]:
X_train

array([[-1.44118078, -0.80602824, -0.52522573, ..., -1.19560192,
        -0.94366888, -1.21106014],
       [ 0.64994428,  1.24065132,  1.90394328, ..., -1.19560192,
         1.05969374,  0.82572282],
       [-1.44118078, -0.80602824, -0.52522573, ..., -1.19560192,
        -0.94366888, -1.21106014],
       ...,
       [-0.39561825, -0.80602824, -0.52522573, ...,  0.977457  ,
        -0.94366888,  0.82572282],
       [ 0.64994428,  1.24065132,  1.90394328, ..., -0.10907246,
        -0.94366888,  0.82572282],
       [-1.44118078, -0.80602824, -0.52522573, ..., -1.19560192,
        -0.94366888, -1.21106014]])

In [64]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(259,17)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0,2),
    tf.keras.layers.Dense(10, activation='softmax')
]) 

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [65]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [66]:
model.fit(X_train,y_train,epochs=5)

Epoch 1/5


ValueError: in user code:

    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\engine\training.py", line 1249, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\engine\training.py", line 1233, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\engine\training.py", line 1222, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\engine\training.py", line 1023, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\tariv\anaconda3\lib\site-packages\keras\engine\input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential_4" is incompatible with the layer: expected shape=(None, 259, 17), found shape=(None, 17)


In [86]:
X_train.shape

(60000, 28, 28)

In [63]:
y_train.shape

(259,)

In [85]:
X_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [68]:
import tensorflow as tf
from tensorflow import keras

In [73]:
fashiondata = tf.keras.datasets.mnist

In [74]:
(X_train,y_train),(x_test,y_test) = fashiondata.load_data()

11490434/11490434 [==============================] - 3s 0us/step


In [79]:
type(X_train)

numpy.ndarray

In [80]:
X_train.shape

(60000, 28, 28)

In [83]:
y_test.shape

(10000,)

In [90]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0,2),
    tf.keras.layers.Dense(10, activation='softmax')
]) 

In [91]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [92]:
model.fit(X_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 2.2209 - accuracy: 0.8578
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3561 - accuracy: 0.9133
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2774 - accuracy: 0.9295
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2556 - accuracy: 0.9347
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2348 - accuracy: 0.9403


In [93]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 0s 920us/step - loss: 0.2596 - accuracy: 0.9392


[0.2596006393432617, 0.9391999840736389]